#!/bin/sh

#_(
  "exec" "bb" "-I" "$0" "$@"
  )

(require '[babashka.deps :as deps])
(deps/add-deps '{:deps {justone/bb-scripts {:local/root "."}}})
(require '[comb])

(when (= *file* (System/getProperty "babashka.file"))
  (apply comb/-main *command-line-args*))
